inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'

plugins:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-performance